cmake now supports swemu, task_sqrt's bundle names are changed---task kernels sqrt and matops have problems

diff --git a/scripts/LaunchDeepPointV1FPGA.sh.in b/scripts/LaunchDeepPointV1FPGA.sh.in
--- a/scripts/LaunchDeepPointV1FPGA.sh.in
+++ b/scripts/LaunchDeepPointV1FPGA.sh.in
@@ -22,6 +22,14 @@ platform=@DSA_NAME@
 hostsideexe=@HostExecutablePath@
 datadir=@DataDirectory@
 
+if [ -e $hostsideexe ]
+then
+    echo -e "${GREEN}Found The Host Executable: ${hostsideexe}${NC}"
+else
+    echo -e "${RED}ERROR${NC}: The required host program(${hostsideexe}) was not found. Please run $ make DeepPointV1FPGA ."
+    exit 1
+fi
+
 case $mode in
 1)      
 	#------------------------------------------Checking if xclbin exists:
